/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bandtec.lista03.poo;

import javax.swing.JProgressBar;

/**
 *
 * @author guilh
 */
public class TelaEx2 extends javax.swing.JFrame {
    Lutador lutador01 = new Lutador();
    Lutador lutador02 = new Lutador();
    void ApanharP(){
    if(lutador01.Vida > 0 && lutador02.Vida > 0){
    lutador02.Apanhar();
    Perdeu();
    }
    }
    void CForcaP(){
    if(lutador01.Vida > 0 && lutador02.Vida > 0){
        lutador02.CForca();
        Perdeu();
    }
    
    }
    void ApanharP1(){
    if(lutador01.Vida > 0 && lutador02.Vida > 0){
    lutador01.Apanhar();
    Perdeu();
    }
    }
    void CForcaP1(){
    if(lutador01.Vida > 0 && lutador02.Vida > 0){
        lutador01.CForca();
        Perdeu();
    }
    
    }
    
    void AtualizarInformacoes(JProgressBar Vida, Lutador Lutador0101){
    Vida.setValue(Lutador0101.Vida);
    }
    void Perdeu(){
    if(lutador01.Vida <= 0){
    lblLutPerd.setText("Lutador01 Perdeu");
    
    }else if(lutador02.Vida <=0){
    lblLutPerd.setText("Lutador02 Perdeu");
    }
    
    
    }
    /**
     * Creates new form TelaEx2
     */
    public TelaEx2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PbLt02 = new javax.swing.JProgressBar();
        PbLt01 = new javax.swing.JProgressBar();
        btApanh01 = new javax.swing.JButton();
        btCForca01 = new javax.swing.JButton();
        btnLt02 = new javax.swing.JButton();
        btCForca02 = new javax.swing.JButton();
        lblLutPerd = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PbLt02.setValue(100);

        PbLt01.setValue(100);

        btApanh01.setText("Apanhar");
        btApanh01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btApanh01ActionPerformed(evt);
            }
        });

        btCForca01.setText("Concentrar Força");
        btCForca01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCForca01ActionPerformed(evt);
            }
        });

        btnLt02.setText("Apanhar");
        btnLt02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLt02ActionPerformed(evt);
            }
        });

        btCForca02.setText("Concentrar Força");
        btCForca02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCForca02ActionPerformed(evt);
            }
        });

        lblLutPerd.setText("Lutador-- Perdeu");

        jLabel2.setText("Lutador01");

        jLabel3.setText("Lutador02");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(lblLutPerd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PbLt01, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PbLt02, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnLt02, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btCForca02))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(btApanh01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(btCForca01)))))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PbLt01, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btApanh01)
                    .addComponent(btCForca01))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PbLt02, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLt02)
                    .addComponent(btCForca02))
                .addGap(33, 33, 33)
                .addComponent(lblLutPerd)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btApanh01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApanh01ActionPerformed

        ApanharP1();
        AtualizarInformacoes(PbLt01, lutador01);
        
    }//GEN-LAST:event_btApanh01ActionPerformed

    private void btCForca01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCForca01ActionPerformed
        CForcaP1();
        AtualizarInformacoes(PbLt01, lutador01);
    }//GEN-LAST:event_btCForca01ActionPerformed

    private void btnLt02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLt02ActionPerformed
        ApanharP();
        AtualizarInformacoes(PbLt02, lutador02);
    }//GEN-LAST:event_btnLt02ActionPerformed

    private void btCForca02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCForca02ActionPerformed
        CForcaP();
        AtualizarInformacoes(PbLt02, lutador02);
    }//GEN-LAST:event_btCForca02ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEx2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEx2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEx2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEx2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEx2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar PbLt01;
    private javax.swing.JProgressBar PbLt02;
    private javax.swing.JButton btApanh01;
    private javax.swing.JButton btCForca01;
    private javax.swing.JButton btCForca02;
    private javax.swing.JButton btnLt02;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblLutPerd;
    // End of variables declaration//GEN-END:variables
}
