/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bandtec.lista03.poo;

import javax.swing.JLabel;

/**
 *
 * @author guilh
 */
public class TelaEx3 extends javax.swing.JFrame {
    Elevador elevador01 = new Elevador();
    Elevador elevador02 = new Elevador();
    /**
     * Creates new form TelaEx3
     */
    void AtualizarInformacoes(JLabel Peso, JLabel NumPessoas, Elevador elevador0101){
       Peso.setText(elevador0101.PesoElevador.toString());
       NumPessoas.setText(elevador0101.NumPessoas.toString());
    }
    public TelaEx3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btEntHomem01 = new javax.swing.JButton();
        btEntMulher01 = new javax.swing.JButton();
        btEntCrianca01 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblPassElev01 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPesoElev01 = new javax.swing.JLabel();
        btEntHomem3 = new javax.swing.JButton();
        btEntMulher3 = new javax.swing.JButton();
        btEntCrianca3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblPassElev3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblPesoElev3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btEntHomem01.setText("Entrar Homem");
        btEntHomem01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntHomem01ActionPerformed(evt);
            }
        });

        btEntMulher01.setText("Entrar Mulher");
        btEntMulher01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntMulher01ActionPerformed(evt);
            }
        });

        btEntCrianca01.setText("Entrar Criança");
        btEntCrianca01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntCrianca01ActionPerformed(evt);
            }
        });

        jLabel1.setText("Total de Passageiros No Elevador:");

        lblPassElev01.setText("0");

        jLabel3.setText("Peso Total No Elevador:");

        lblPesoElev01.setText("0");

        btEntHomem3.setText("Entrar Homem");
        btEntHomem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntHomem3ActionPerformed(evt);
            }
        });

        btEntMulher3.setText("Entrar Mulher");
        btEntMulher3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntMulher3ActionPerformed(evt);
            }
        });

        btEntCrianca3.setText("Entrar Criança");
        btEntCrianca3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntCrianca3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Total de Passageiros No Elevador:");

        lblPassElev3.setText("0");

        jLabel6.setText("Peso Total No Elevador:");

        lblPesoElev3.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btEntHomem01)
                        .addGap(18, 18, 18)
                        .addComponent(btEntMulher01)
                        .addGap(18, 18, 18)
                        .addComponent(btEntCrianca01))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPassElev01))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPesoElev01)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btEntHomem3)
                        .addGap(18, 18, 18)
                        .addComponent(btEntMulher3)
                        .addGap(18, 18, 18)
                        .addComponent(btEntCrianca3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPassElev3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPesoElev3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEntHomem01)
                    .addComponent(btEntMulher01)
                    .addComponent(btEntCrianca01))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblPassElev01))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblPesoElev01))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEntHomem3)
                    .addComponent(btEntMulher3)
                    .addComponent(btEntCrianca3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblPassElev3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblPesoElev3))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEntCrianca01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntCrianca01ActionPerformed
        elevador01.Crianca();
        elevador01.EntrarPessoa();
        AtualizarInformacoes(lblPesoElev01, lblPassElev01, elevador01);
    }//GEN-LAST:event_btEntCrianca01ActionPerformed

    private void btEntHomem01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntHomem01ActionPerformed
        elevador01.Homem();
        elevador01.EntrarPessoa();
        AtualizarInformacoes(lblPesoElev01, lblPassElev01, elevador01);
    }//GEN-LAST:event_btEntHomem01ActionPerformed

    private void btEntMulher01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntMulher01ActionPerformed
        elevador01.Mulher();
        elevador01.EntrarPessoa();
        AtualizarInformacoes(lblPesoElev01, lblPassElev01, elevador01);
    }//GEN-LAST:event_btEntMulher01ActionPerformed

    private void btEntHomem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntHomem3ActionPerformed
        elevador02.Homem();
        elevador02.EntrarPessoa();
        AtualizarInformacoes(lblPesoElev3, lblPassElev3, elevador02);
    }//GEN-LAST:event_btEntHomem3ActionPerformed

    private void btEntMulher3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntMulher3ActionPerformed
        elevador02.Mulher();
        elevador02.EntrarPessoa();
        AtualizarInformacoes(lblPesoElev3, lblPassElev3, elevador02);
    }//GEN-LAST:event_btEntMulher3ActionPerformed

    private void btEntCrianca3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntCrianca3ActionPerformed
        elevador02.Crianca();
        elevador02.EntrarPessoa();
        AtualizarInformacoes(lblPesoElev3, lblPassElev3, elevador02);
    }//GEN-LAST:event_btEntCrianca3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEx3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEx3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEx3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEx3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEx3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEntCrianca01;
    private javax.swing.JButton btEntCrianca3;
    private javax.swing.JButton btEntHomem01;
    private javax.swing.JButton btEntHomem3;
    private javax.swing.JButton btEntMulher01;
    private javax.swing.JButton btEntMulher3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblPassElev01;
    private javax.swing.JLabel lblPassElev3;
    private javax.swing.JLabel lblPesoElev01;
    private javax.swing.JLabel lblPesoElev3;
    // End of variables declaration//GEN-END:variables
}
